djangodelights/djangodelights/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('inventory.urls')),
    path('admin/', admin.site.urls),
]

djangodelights/inventory/urls.py
from django.urls import path, register_converter
from django.contrib.auth import views as auth_views

from . import views
from .converters import DateConverter

register_converter(DateConverter, 'date')

# selection_reports http://127.0.0.1:8000/selection_reports/?start_date=2023-08-09&end_date=2023-08-10
#
urlpatterns = [    
    path('logout/', views.LogOut, name='logout'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('', views.HomeView.as_view(), name='home'), 
    path('ingredients/', views.IngredientsView.as_view(), name="ingredients"),
    path('ingredients/new', views.NewIngredientView.as_view(), name="add_ingredient"),
    path('ingredients/<slug:pk>/update', views.UpdateIngredientView.as_view(), name="update_ingredient"),    
    path('menu/', views.MenuView.as_view(), name="menu"),
    path('menu/new', views.NewMenuItemView.as_view(), name="add_menu_item"),
    path('menu/<slug:pk>/update', views.UpdateMenuItemView.as_view(), name="update_menu_item"),
    path('reciperequirement/new', views.NewRecipeRequirementView.as_view(), name="add_recipe_requirement"),
    path('reciperequirement/<slug:pk>/update', views.UpdateRecipeRequirementView.as_view(), name="update_recipe_requirement"), 
    path('reciperequirement/<int:menu_item>/new', views.NewRecipeRequirementToMenuItemView.as_view(), name="add_recipe_requirement_to_menu_item"),   
    path('purchases/', views.PurchasesView.as_view(), name="purchases"),
    path('purchases/new', views.NewPurchaseView.as_view(), name="add_purchase"), 
    path('purchases/new_search', views.PurchaseSearchAddView, name="search_add_purchase"), 
    path('reports/', views.ReportView.as_view(), name="reports"),
    path('selection_reports/<date:start_date>/', views.ReportDateSelectionView, name="selection_reports"),   
    path('selection_reports/', views.ReportDateSelectionView, name="selection_reports"),  
           
    
]

djangodelights/inventory/models.py
from django.db import models

# Create your models here.

class Ingredient(models.Model):
    ##
    # An ingredient should have the following fields (at least):
    #name: the name of the ingredient (i.e. flour)
    #quantity: the quantity of the ingredient available in the inventory (i.e. 4.5)
    #unit: the unit used for the ingredient (i.e. tbsp or lbs)
    #unit_price: the price per unit of the ingredient (i.e. 0.05, for a tbsp of flour)
    ##
    
    class UnitType(models.TextChoices):
        GRAM = "g"
        CENTILITER = "cl"
        KOFFIELEPEL = "kl"
        EETLEPEL = "el"
        STUK = "stk"

    name = models.CharField(max_length=200)
    quantity = models.FloatField(default=0.00, verbose_name="quantity in stock")    
    unit = models.CharField(blank=True, choices=UnitType.choices, max_length=15)    
    unit_price = models.FloatField(default=0.00)

    def get_absolute_url(self):
        return "/ingredients"

    def __str__(self):
        return f"""
        name={self.name};
        qty_in_stock={self.quantity};
        unit={self.unit};
        unit_price={self.unit_price}
        """
    
class MenuItem(models.Model):
    ##
    #A menu item should have the following fields (at least):
    #- **`title`**: the title of the item on the menu (i.e. `Django Juice`)
    #- **`price`**: the price of the item (i.e. `3.49` for a glass)
    title = models.CharField(max_length=200)
    price = models.FloatField(default=0.00)

    def __str__(self):
        return f"""
        title={self.title};
        price={self.price}
        """
    
    def get_absolute_url(self):
        return "/menu"
    
    def available(self):
        return all(X.enough() for X in self.reciperequirement_set.all())

    def cost(self):   
        ## Voor de Jaffa Cake
        #Jaffa Cake
        #Chocolade 150g 0.00675 = 1.0125
        #Bloem 100g 0.00425 = 0.425
        #Rietsuiker 150g 0.00089 = 0.1335
        #Ei 1st 0.25 = 0.25
        #Confituur 100g 0.00089 = 0.089
        # Total Cost 1.91
        # Total Profit = 5.00 - 1,91 = 3.09
        ##
        #total_cost = all(X.cost() for X in self.reciperequirement_set.all())
        # all geeft een true of false of mee dus waarde 1 dit geeft dan dat profit 4 is 5.0 - 1 = 4.0     
        total_cost = 0
        for X in self.reciperequirement_set.all() :
            total_cost = total_cost + X.cost()  
        return total_cost
    
    def profit(self):                
        total_profit = self.price - self.cost()
        return total_profit
    
    
    
class RecipeRequirement(models.Model):
    ## `RecipeRequirement`
    #This model represents a single ingredient and how much of it is required for an item off the menu.
    #A recipe requirement should have the following fields (at least):
    #- **`menu_item`**: a reference to an item on the menu (i.e. a foreign key to the `MenuItem` model)
    #- **`ingredient`**: a reference to a required ingredient for the associated menu item (i.e. a foreign key to the `Ingredient` model)
    #- **`quantity`**: the amount of the associated ingredient that is required to create the menu item (i.e. `1.5` ounces of `sugar` to create `Django Djaffa Cake`)
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField(default=0.00)

    def __str__(self):
        return f"""
        menu_item=[{self.menu_item.__str__()}];
        ingredient={self.ingredient.name};
        qty={self.quantity}
        """
    
    def get_absolute_url(self):
        return "/menu"
            
    def enough(self):        
        return self.quantity <= self.ingredient.quantity
            
    def cost(self):        
        return self.quantity * self.ingredient.unit_price

class Purchase(models.Model):
    ## `Purchase`
    #This model represents a customer purchase of an item off the menu.
    #A purchase should have the following fields (at least):
    #- **`menu_item`**: a reference to an item on the menu (i.e. a foreign key to the `MenuItem` model)
    #- **`timestamp`**: a timestamp indicating the time that the purchase was recorded (i.e. a `DateTimeField`)
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=0, verbose_name="quantity ordered")    

    def __str__(self):
        return f"""
        menu_item=[{self.menu_item.__str__()}];
        time={self.timestamp}
        """
    
    def get_absolute_url(self):
        return "/purchases"
    

djangodelights/inventory/views.py
import datetime
from django.shortcuts import redirect, render
from django.urls import reverse

from django.contrib.auth import logout

from django.db.models import Q
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Ingredient, MenuItem, Purchase, RecipeRequirement
from .forms import IngredientForm, MenuItemForm, RecipeRequirementForm, RecipeRequirementMenuItemForm, ReportDateSelectionForm, PurchaseSearchAddForm

# Create your views here.

def LogOut(request):
    logout(request)
    return redirect("/")

class HomeView(LoginRequiredMixin,TemplateView):
    # 
    template_name = "inventory/home.html"

    def get_context_data(self, *args, **kwargs):
        context = context = super().get_context_data(*args, **kwargs)
        context['menu_items'] = MenuItem.objects.all()
        context['ingredients'] = Ingredient.objects.all()
        context['purchases'] = Purchase.objects.all()        
        return context

class IngredientsView(LoginRequiredMixin,ListView):
    template_name = "inventory/ingredients_list.html"
    model = Ingredient

class NewIngredientView(LoginRequiredMixin,CreateView):
    model = Ingredient
    template_name = "inventory/add_ingredient.html"
    form_class = IngredientForm

class UpdateIngredientView(LoginRequiredMixin,UpdateView):
    model = Ingredient
    template_name = "inventory/update_ingredient.html"
    form_class = IngredientForm

class MenuView(LoginRequiredMixin,ListView):
    template_name = "inventory/menu_list.html"
    model = MenuItem

class NewMenuItemView(LoginRequiredMixin,CreateView):
    model = MenuItem
    template_name = "inventory/add_menu_item.html"
    form_class = MenuItemForm

class UpdateMenuItemView(LoginRequiredMixin,UpdateView):
    model = MenuItem
    template_name = "inventory/update_menu_item.html"
    form_class = MenuItemForm

class NewRecipeRequirementView(LoginRequiredMixin,CreateView):
    model = RecipeRequirement
    template_name = "inventory/add_recipe_requirement.html"
    form_class = RecipeRequirementForm    

class NewRecipeRequirementToMenuItemView(LoginRequiredMixin,CreateView):
    model = RecipeRequirement
    template_name = "inventory/add_recipe_requirement.html"
    form_class = RecipeRequirementMenuItemForm

    def form_valid(self, form):
        form.instance.menu_item_id = self.kwargs['menu_item']
        return super().form_valid(form)

class UpdateRecipeRequirementView(LoginRequiredMixin,UpdateView):
    model = RecipeRequirement
    template_name = "inventory/update_recipe_requirement.html"
    form_class = RecipeRequirementForm  

class PurchasesView(LoginRequiredMixin,ListView):
    model =Purchase
    template_name = "inventory/purchase_list"

class NewPurchaseView(LoginRequiredMixin,TemplateView):
    # 
    template_name = "inventory/add_purchase.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # De menu_items die we tonen zijn alleen de menu_items die available zijn
        context['menu_items'] =[X for X in MenuItem.objects.all() if X.available()]              
        return context
    
    def post(self, request):
        menu_item_id = request.POST["menu_item"]
        qty_purchased = float(request.POST["quantity"])
        menu_item = MenuItem.objects.get(pk=menu_item_id)
        requirements = menu_item.reciperequirement_set
        purchase = Purchase(menu_item=menu_item,quantity=qty_purchased)

        for requirement in requirements.all():
            required_ingredient = requirement.ingredient
            required_ingredient.quantity -= (requirement.quantity*qty_purchased) 
            required_ingredient.save()

        purchase.save()
        return redirect("/purchases")

class ReportView(LoginRequiredMixin,TemplateView):
    template_name = "inventory/reports.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["purchases"] = Purchase.objects.all()
        revenue = 0
        total_cost = 0
        
        #revenue = Purchase.objects.aggregate(
        #    revenue=Sum("menu_item__price"))["revenue"]
            
        for purchase in Purchase.objects.all():
            revenue += purchase.menu_item.price * purchase.quantity

        for purchase in Purchase.objects.all():
            for recipe_requirement in purchase.menu_item.reciperequirement_set.all():
                total_cost += recipe_requirement.ingredient.unit_price * \
                    recipe_requirement.quantity * \
                    purchase.quantity

        context["revenue"] = revenue
        context["total_cost"] = total_cost
        context["profit"] = revenue - total_cost

        return context

def ReportDateSelectionView(request, start_date=datetime.date.today(), end_date=datetime.date.today()):
    
     # If this is a POST request then process the Form data
    if request.method == 'POST':        
        # Create a form instance and populate it with data from the request (binding):
        form = ReportDateSelectionForm(request.POST)        
        # Form is  valid:
        if form.is_valid():                        
            startdate = form.cleaned_data['startdate']
            enddate = form.cleaned_data['enddate']            
            purchases = Purchase.objects.filter(
                timestamp__date__range=(startdate,enddate)  
            )  
            str_startdate=startdate.strftime('%Y-%m-%d')
            str_enddate=enddate.strftime('%Y-%m-%d')            
            my_querystring="%s?start_date=" + str_startdate + "&end_date=" + str_enddate           
            return redirect(my_querystring % reverse('selection_reports'))
        #           
        # Form is not valid:
        if not form.is_valid():  
          ###  <ul class="errorlist"><li>Invalid date - renewal in past</li></ul>                      
          return render(request,"inventory/reports_date_selection.html", {'form':form})

            
    # If this is a GET (or any other method) create the default form.
    else:
        # Try to handle this : http://127.0.0.1:8000/selection_reports/?start_date=2023-08-09&end_date=2023-08-10
        start_date = request.GET.get('start_date', datetime.date.today() )
        end_date = request.GET.get('end_date', datetime.date.today())  
        purchases = Purchase.objects.filter(
            timestamp__date__range=(start_date,end_date)           
        )
           
        form = ReportDateSelectionForm(initial={'startdate': start_date,
                                                'enddate': end_date})
        revenue = 0
        total_cost = 0
        for purchase in purchases:
            revenue += purchase.menu_item.price * purchase.quantity

        for purchase in purchases:
            for recipe_requirement in purchase.menu_item.reciperequirement_set.all():
                total_cost += recipe_requirement.ingredient.unit_price * \
                    recipe_requirement.quantity * \
                    purchase.quantity

                                             
        context = {
            'form': form,
            'purchases' : purchases,
            'revenue' : revenue,
            'purchases' : purchases,
            'revenue' : revenue,
            'total_cost' : total_cost,
            'profit' : revenue - total_cost,
        }           

        return render(request, "inventory/reports_date_selection.html", context)

def PurchaseSearchAddView(request):
    # 
    # If this is a POST request then process the Form data
    if request.method == 'POST':        
        # Create a form instance and populate it with data from the request (binding):
        form = PurchaseSearchAddForm(request.POST)        
        # Form is  valid:
        if form.is_valid():             
            form_search = form.cleaned_data['form_search']
            ###values = Blog.objects.filter(name__contains="Cheddar").values_list("pk", flat=True)
            ###entries = Entry.objects.filter(blog__in=list(values))
            #available_menu_items =[X for X in MenuItem.objects.all() if X.available()]
            available_menu_items = [X for X in MenuItem.objects.filter(title__icontains=form_search) if X.available()]

            context = {
                'form': form,  
                'menu_items': available_menu_items,  
                'menu_items_found': len(available_menu_items),                  
            }              
            return render(request, "inventory/add_search_purchase.html", context)
        #           
        # Form is not valid:
        if not form.is_valid():     
          ###  <ul class="errorlist"><li>Invalid date - renewal in past</li></ul>                      
          return render(request,"inventory/add_search_purchase.html", {'form':form})
          
    # If this is a GET (or any other method) create the default form.
    else:       
        available_menu_items = [X for X in MenuItem.objects.all() if X.available()]            
        form = PurchaseSearchAddForm()        
                                             
        context = {
            'form': form, 
            'menu_items': available_menu_items, 
            'menu_items_found': len(available_menu_items),                    
        }           

        return render(request, "inventory/add_search_purchase.html", context)

djangodelights/inventory/templates/inventory/add_ingredient.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Add Ingredient to Inventory</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

djangodelights/inventory/templates/inventory/add_menu_item.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Add Item to Menu</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

djangodelights/inventory/templates/inventory/add_purchase.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Enter a new purchase</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <p>
        <label for="menu_item">Menu item:</label>
        <select name="menu_item" id="menu_item" required>
            <option value selected>-----</option>
        {% for menu_item in menu_items %}
            <option value={{ menu_item.id }}>{{ menu_item.title }}</option>
        {% endfor %}
        </select>
        <label for="quantity">Quantity: </label>
        <input id="quantity" type="number" name="quantity" value="1" required>
    </p>
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

djangodelights/inventory/templates/inventory/add_recipe_requirement.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Add Recipe Requirement for a Menu Item</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

djangodelights/inventory/templates/inventory/add_search_purchase.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Search and add a new purchase</h2>
    <form method="post">
    <div>
    {% csrf_token %} 
    <i class="material-icons">search</i>  
    <hr>
    {% comment %}{% endcomment %}
    <label for="id_{{ form.form_search.name }}" class="control-label">{{ form.form_search.label }}</label>
    {{ form.form_search }} 
    <input type="submit" value="Search"/>
    <hr>       
    
    <table class="inventory-table">
        <thead>
            <tr>
                <th>Checkbox</th>
                <th>Title</th>
                <th>Quantity</th>                
            </tr>
        </thead>
        <tbody>
            {% for menu_item in menu_items %} 
                <tr>
                    <td></td>
                    <td>{{ menu_item.title }}</td>         
                    <td class="price"></td>                              
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <hr>
    Number of Menus : {{ menu_items_found }}

    </div>
    </form>
{% endblock %}

djangodelights/inventory/templates/inventory/home.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Delights{% endblock %}
{% block content %}
    <div class="home">
        <div>
            <h2>Ingredients</h2>
            <table class="inventory-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th class="price">Quantity</th>
                        <th>Unit</th>
                        <th class="price">Unit Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for ingredient in ingredients %}
                    <tr>
                        <td>{{ ingredient.name }}</td>
                        <td class="price">{{ ingredient.quantity|stringformat:".2f" }}</div></td>                        
                        <td>{{ ingredient.get_unit_display }}</td>
                        <td class="price">€ {{ ingredient.unit_price|stringformat:".5f" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <hr/>

        <div>
            <h2>Purchases</h2>
            <table class="inventory-table">
                <thead>
                    <tr>
                        <th>Menu Item</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody>
                {% for purchase in purchases %}
                    <tr>
                        <td>{{ purchase.menu_item.title }}</td>
                        <td class="price">${{ purchase.menu_item.price|stringformat:".2f" }}</td>
                        <td class="price">${{ purchase.quantity }}</td>
                        <td>{{ purchase.timestamp }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <hr/>       

    <div>
        <h2>Menu</h2>
        {% for menu_item in menu_items %}   
            <table class="inventory-table">
                <thead>
                    <tr>
                        <th>{{ menu_item.title }} : € {{ menu_item.price|stringformat:".2f" }}</th>                   
                    </tr>
                </thead>
                <tbody>            
                    {% for recipe_requirement in menu_item.reciperequirement_set.all %}
                    <tr>
                        <td>                    
                        {{ recipe_requirement.quantity }} {{recipe_requirement.ingredient.get_unit_display }} {{ recipe_requirement.ingredient.name }}                    
                        </td>                  
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endfor %}
    </div>

{% endblock %}

djangodelights/inventory/templates/inventory/ingredients_list.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Delights{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
    <h2>Ingredients</h2>
    <a href="{% url 'add_ingredient' %} ">Add New Ingredient to Inventory</a>
    <hr/>
    <table class="inventory-table">
        <thead>
            <tr>
                <th>Name</th>
                <th class="price">Quantity</th>
                <th>Unit</th>
                <th class="price">Unit Price</th>
            </tr>
        </thead>
        <tbody>
        {% for ingredient in object_list %}
            <tr>
                <td>
                    <a href="{% url "update_ingredient" ingredient.id %}">{{ ingredient.name }}</a>
                </td>
                <td class="price">{{ ingredient.quantity }}</td>
                <td>{{ ingredient.get_unit_display }}</td>
                <td class="price">€ {{ ingredient.unit_price|stringformat:".5f" }}</td>                
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

djangodelights/inventory/templates/inventory/menu_list.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Delights{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
    <h2>Menu</h2>
    <p><a href="{% url 'add_menu_item' %}">Add New Item to Menu</a></p>  
    {% comment %} {% endcomment %}               
    <hr/>
    <ul class="menu-items">
    {% for menu_item in object_list %}
        <li>
            <div class="menu-item-header">
                <div class="menu-item-title"> <a href="{% url "update_menu_item" menu_item.id %}">{{ menu_item.title }}</a></div>                
                {% if menu_item.available is False %}<div class="menu-item-available">Not available</div>{% endif %}
                <div class="menu-item-price">€ {{ menu_item.price|stringformat:".2f" }}</div>
            </div>
            <p><a href="{% url 'add_recipe_requirement_to_menu_item' menu_item.id %}">Add Recipe Requirement</a></p>
            <ul class="menu-item-ingredients">                
                {% for recipe_requirement in menu_item.reciperequirement_set.all %}                
                <li><a href="{% url 'update_recipe_requirement' recipe_requirement.id %} ">
                    {% if recipe_requirement.enough is False %}
                        <div class="menu-item-available">
                            {{ recipe_requirement.quantity }}
                            {{recipe_requirement.ingredient.get_unit_display }}
                            {{ recipe_requirement.ingredient.name }}
                        </div>
                    {% else %}
                        {{ recipe_requirement.quantity }}
                        {{recipe_requirement.ingredient.get_unit_display }}
                        {{ recipe_requirement.ingredient.name }}
                    {% endif %}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

djangodelights/inventory/templates/inventory/purchase_list.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
{% endblock %}
{% block content %}
    <h2>Purchases</h2>
    <a href="{% url 'add_purchase' %}">Record New Purchase</a>      
    <hr/>
    <table class="inventory-table">
        <thead>
            <tr>
                <th>Menu Item</th>
                <th class="price">Price</th>
                <th class="price">Quantity</th>
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
        {% for purchase in object_list %}
            <tr>
                <td>{{ purchase.menu_item.title }}</td>
                <td class="price">€ {{ purchase.menu_item.price|stringformat:".2f" }}</td>
                <td class="price">{{ purchase.quantity }}</td>
                <td>{{ purchase.timestamp }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

djangodelights/inventory/templates/inventory/reports.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
{% endblock %}
{% block content %}
    <h2>Purchases</h2>
    <table class="inventory-table">
        <thead>
            <tr>
                <th>Menu Item</th>
                <th class="price">Price</th>
                <th class="price">Quantity</th> 
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
        {% for purchase in purchases %}
            <tr>
                <td>{{ purchase.menu_item.title }}</td>
                <td class="price">€ {{ purchase.menu_item.price|stringformat:".2f" }}</td>
                <td class="price">€{{ purchase.quantity|stringformat:".2f" }}</td>
                <td>{{ purchase.timestamp }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr/>
    <h2>Totals</h2>
    <div style="color: green;">Total Revenue: € {{ revenue|stringformat:".2f" }}</div>
    <div style="color: red;">Total Cost: € {{ total_cost|stringformat:".2f" }}</div>
    <div style="color: blue;">Total Profit: € {{ profit|stringformat:".2f" }}</div>
{% endblock %}

djangodelights/inventory/templates/inventory/reports_date_selection.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
{% endblock %}
{% block content %}
    <h2>Purchases</h2>
    <table class="inventory-table">
        <thead>
            <tr>
                <th>Menu Item</th>
                <th class="price">Price</th>
                <th class="price">Quantity</th> 
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
        {% for purchase in purchases %}
            <tr>
                <td>{{ purchase.menu_item.title }}</td>
                <td class="price">€ {{ purchase.menu_item.price|stringformat:".2f" }}</td>
                <td class="price">€{{ purchase.quantity|stringformat:".2f" }}</td>
                <td>{{ purchase.timestamp }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <form method="post">
    	{% csrf_token %}
        {{form}}
        <button class="btn btn-primary">Submit</button>
    </form>
    
    <div style="color: green;">Total Revenue: € {{ revenue|stringformat:".2f" }}</div>
    <div style="color: red;">Total Cost: € {{ total_cost|stringformat:".2f" }}</div>
    <div style="color: blue;">Total Profit: € {{ profit|stringformat:".2f" }}</div>
{% endblock %}

djangodelights/inventory/templates/inventory/update_ingredient.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Update Ingredient in Inventory</h2>
    <form method="post" class="flex-form">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Update"/>
    </form>
{% endblock %}

djangodelights/inventory/templates/inventory/update_menu_item.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Update Menu Item</h2>
    <form method="post" class="flex-form">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Update"/>
    </form>
{% endblock %}

djangodelights/inventory/templates/inventory/update_recipe_requirement.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Update Recipe requirement in Inventory</h2>
    <form method="post" class="flex-form">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Update"/>
    </form>
{% endblock %}